name: Run PHPUnit tests
run-name: ${{ github.actor }} is running unit tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Validate composer.json
        run: composer validate --strict
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run tests
        run: composer run-script test
      - run: echo "This job's status is ${{ job.status }}."
